### PR TITLE
Updates to some langugage files

### PR DESCRIPTION
**Pull request by Creatium**
Updated files as required

### CODE REVIEW

**Comment by meangczac** [comment]
Sorry, just saw this now.

**Comment by meangczac** [comment]
Err... Can't auto merge. I ask for help! Lol..

**Comment by Creatium** [comment]
Not sure if I can do something?

**Comment by rimelek** [comment]
I managed to merge it. There is a new line added by hien that caused the conflict. Please, translate it on line 409:

``` php
$locale['qedit'] = 'Quick Edit';
```

**Pull request merged**
