### PR TITLE
Fix Securimage 2

### PR DESCRIPTION
**Pull request by RobiNN1**
Update to v2.0.2 

Please delete Securimage v1 is not supported

Create new Securimage v3
[securimage3.zip](https://github.com/php-fusion/PHP-Fusion/files/445204/securimage3.zip)

### CODE REVIEW

**Comment by RobiNN1** [comment]
Update to 2.0.2

**Comment by meangczac** [comment]
Is the codes secure image 2 or 3? Can you push together the new secure image 3?

I leave unmerged at this moment. Please tell me what to do? Also we should just leave secure image pack at 1 type only... the parcel is quite big.

**Comment by RobiNN1** [comment]
Delete old v1.
V2 is now working and upload new v3 in zip file I tested and work well.
In pull request is fixed v2 and I do not permission to upload v3.
Or delete v1 and v2, v3 have only.

**Comment by meangczac** [comment]
Ok, lets delete v1. I'll add v3 directly. I won't test it yet ok. Busy with the Nebula.

**Comment by meangczac** [comment]
https://github.com/php-fusion/PHP-Fusion/commit/185abdbaf5d6caa0db9d7ac32f50af5cd410d1ea

**Pull request merged**
