### PR TITLE
Update Errors.php

### PR DESCRIPTION
**Pull request by RobiNN1**

### CODE REVIEW

**Comment by Catzenjaeger** [comment]
plz add the error messages on top of all pages. Its bother when i have to scroll again and again. Place it on head and all is good and more userfriendly

**Comment by meangczac** [comment]
hahaha.. top is better? Wait for Notifications API I'm gonna build for RC5. There will be a bell.... lolol

**Comment by Catzenjaeger** [comment]
yes in header and not in footer .. when i test i have to scroll again and again and this is worst hehe

**Comment by meangczac** [comment]
Fact: Version 7, you can only see error logs in the admin page. Let's just leave at that and focus on more important things.

Btw, no need to scroll..... just long press "spacebar" or "End" key ... for up, click "Home" button. It's not that difficult.

home end pg up dn desktop

**Comment by Catzenjaeger** [comment]
no problem you are right ... my intension was only more userfriendly / adminfriendly .
I have add this in my theme for myself and it works :)

**Comment by meangczac** [comment]
Understood your point. For code developers, it's good choice. But for theme developer ... no.

capture

I hate it enough already. Adding another in,  I can't design at all.

**Pull request merged**
