### PR TITLE
Start Russian local gallery

### PR DESCRIPTION
**Pull request by zXpycTz**
Creating source files. Edit gallery_admin.php

### CODE REVIEW

**Comment by Rizado** [comment]
Russian locale is added. I'll move it in new folder in 2-3 days.
In fact, you added English text in "Russian" folder. Why?

**Comment by zXpycTz** [comment]
Yesterday began translations. translated several points file gallery_admin.php
Using files enables to see their position and place in the forms. Even without this form Gallery There are no text at all, which makes it not possible to use it.

**Comment by Rizado** [comment]
This is not needed. All files are translated.
I was offline 2 weeks and I didn't have capability to update.

**Comment by zXpycTz** [comment]
I started to use the gallery a few days ago, and the absence of any text disappointing. I'll wait for the publication of localization. 
Thank you for the clarification.

**Comment by Rizado** [comment]
I made completed Russian translation in last year. And I update it when it's needed (excluding last 2 weeks).

**Pull request closed without merging**
