### PR TITLE
HTML buttons should disable referrer on external links.

### PR DESCRIPTION
**Pull request by MPolleke**
HTML buttons should disable referrer on external links.

Reference: PR #2254

### CODE REVIEW

**Comment by RobiNN1** [comment]
is necessary on plain button?

**Comment by MPolleke** [comment]
Most of the links used here will be external buttons. I mostly wanted to add it here as well, for consistency.

**Comment by RobiNN1** [comment]
OK. But this button just adds value to textarea, I don't think we need it here. Also is visible only in settings

**Comment by MPolleke** [comment]
I can live with a no, that is fine :)

**Pull request closed without merging**
