### PR TITLE
Youtube BBCode Update

### PR DESCRIPTION
**Pull request by NetriX-DeV**
Updated youtube embed to reflect latest embed usage standards with
YouTube. Fixed video not displaying on some mobile devices. Removed border=0
as its' deprecated.

### CODE REVIEW

**Comment by Rizado** [comment]
It's good, but size of movie is hardcoded :( .

**Comment by NetriX-DeV** [comment]
The size shouldn't break any themes that I'm aware of.

Or are you proposing a responsive iframe?

**Comment by Rizado** [comment]
As variant:
[youtube=%width%,%height%]%MOVIE_CODE%[/youtube]
If width and height are not specified - use default.

**Comment by NetriX-DeV** [comment]
I don't like the idea of giving that option on one of my sites. The user could break your layout by setting a dimension too high, and the code involved to fix that would over complicate it in my opinion.

Responsive would be a better alternative or:

Maybe a

[youtube=large]VIDEO_ID[/youtube]
[youtube=medium]VIDEO_ID[/youtube]
[youtube=small]VIDEO_ID[/youtube]

**Comment by Rizado** [comment]
You forget that aspect ratio may be different - most popular are 4:3 and 16:9.

**Comment by NetriX-DeV** [comment]
That's what the large, medium, small attributes would be used for.

The current dimensions I set are by YouTube standards.

Width: 560 Height: 315

Both are properly resampled from 720p/1080p resolutions.

What I propose:

Large: 640x360
Medium (Default) 560x315

4:3 was removed back in 2008. Youtube uses 16:9 as the default.

**Pull request merged**
